before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    ldflags:
      - -X main.version={{.Version}}
    binary: timetravel

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

brews:
  - name: timetravel
    homepage: https://github.com/marianina8
    tap:
      owner: marianina8
      name: homebrew-timetravel
    commit_author:
      name: marianina8

release:
  github:
    owner: marianina8
    name: timetravel
  draft: false
  prerelease: auto

dockers:
  - image_templates:
      - "docker.io/marianmontagnino/timetravel:latest"
    dockerfile: Dockerfile
    build_flag_templates:
      - "--no-cache"

nfpms:
  - id: timetravel_386
    package_name: timetravel_386
    formats:
      - deb
      - rpm
    homepage: https://github.com/marianina8/timetravel
    maintainer: Marian Montagnino <mmontagnino@gmail.com>
    description: |-
      Timetravel app installer package for 386 architecture.
      Software for managing time travel configurations.
    license: MIT
    bindir: /usr/bin
    contents:
      - src: ./dist/timetravel_linux_386/timetravel
        dst: /usr/bin/timetravel
  - id: timetravel_amd64
    package_name: timetravel_amd64
    formats:
      - deb
      - rpm
    homepage: https://github.com/marianina8/timetravel
    maintainer: Marian Montagnino <mmontagnino@gmail.com>
    description: |-
      Timetravel app installer package for amd64 architecture.
      Software for managing time travel configurations.
    license: MIT
    bindir: /usr/bin
    contents:
      - src: ./dist/timetravel_linux_amd64_v1/timetravel
        dst: /usr/bin/timetravel
  - id: timetravel_arm64
    package_name: timetravel_arm64
    formats:
      - deb
      - rpm
    homepage: https://github.com/marianina8/timetravel
    maintainer: Marian Montagnino <mmontagnino@gmail.com>
    description: |-
      Timetravel app installer package for arm64 architecture.
      Software for managing time travel configurations.
    license: MIT
    bindir: /usr/bin
    contents:
      - src: ./dist/timetravel_linux_arm64/timetravel
        dst: /usr/bin/timetravel