name: Chocolatey Deploy

on:
  push:
    tags:
      - '*'

defaults:
  run:
    shell: bash

jobs:
  chocolatey:
    name: Deploy
    runs-on: windows-latest
    if: github.repository == 'timetravel'
    steps:
      - name: Clone Repository
        uses: actions/checkout@v4
      - uses: oprypin/find-latest-tag@v1
        with:
          repository: ${{ github.repository }}  # The repository to scan.
          releases-only: true  # We know that all relevant tags have a GitHub release for them.
        id: latesttag
      - name: Set Checksum
        run: |
          filename="timetravel.exe"
          url="https://github.com/${{ github.repository }}/releases/download/${{ steps.latesttag.outputs.tag }}/${filename}"
          sed -i "s#{URL64}#${url}#g" "choco/tools/chocolateyinstall.ps1"
          curl -sSL "${url}" -o "choco/${filename}"
          sha256=$(cat "choco/${filename}" | sha256sum -)
          sed -i "s/{SHA256CHECKSUM64}/${sha256:0:64}/g" "choco/tools/chocolateyinstall.ps1"
      - name: Set Version
        id: version
        run: |
          version=${{ steps.latesttag.outputs.tag }}
          echo "nuget=$version" >> $GITHUB_OUTPUT
          sed -i "s/{VERSION}/${version}/g" "choco/timetravel/timetravel.nuspec"
      - name: Choco Downgrade
        uses: crazy-max/ghaction-chocolatey@v3
        with:
          args: install chocolatey --version=1.2.1 --allow-downgrade -y -r --no-progress
      - name: Pack Release
        uses: crazy-max/ghaction-chocolatey@v3
        with:
          args: pack choco/timetravel/timetravel.nuspec --outputdirectory choco/timetravel
      - name: Choco Upgrade
        uses: crazy-max/ghaction-chocolatey@v3
        with:
          args: upgrade chocolatey
      - name: Upload Release
        uses: crazy-max/ghaction-chocolatey@v3
        with:
          args: push choco/timetravel/timetravel.${{ steps.version.outputs.nuget }}.nupkg -s https://push.chocolatey.org/ -k ${{ secrets.CHOCO_KEY }}